2018-05-30 22:56:12,240 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 22:56:32,796 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 22:56:48,627 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 22:58:18,459 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:00:27,568 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:01:11,895 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:02:46,926 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:03:37,212 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:03:58,241 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:04:16,231 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:05:32,499 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:06:51,138 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:12:12,533 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:12:35,133 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:12:49,030 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:41:00,040 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:42:49,868 ERROR: Exception on /api/measures/from/2018/04/24/to/2018/05/01 [GET] [in /Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lucamaiano/Desktop/visualization/app/api/measures.py", line 20, in get_interval_of_measures
    day = str(year) + '/' + str(month) + '/' + str(day)
NameError: name 'year' is not defined
2018-05-30 23:43:50,850 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:43:53,768 ERROR: Exception on /api/measures/from/2018/04/24/to/2018/05/01 [GET] [in /Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lucamaiano/Desktop/visualization/app/api/measures.py", line 22, in get_interval_of_measures
    print(day)
NameError: name 'day' is not defined
2018-05-30 23:44:09,702 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:44:12,272 ERROR: Exception on /api/measures/from/2018/04/24/to/2018/05/01 [GET] [in /Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lucamaiano/Desktop/visualization/app/api/measures.py", line 23, in get_interval_of_measures
    request = Measurements.query_interval_of_measures(day1, day2)
  File "/Users/lucamaiano/Desktop/visualization/app/models.py", line 148, in query_interval_of_measures
    resources = Measurements.query.filter(day >= day1).filter(day <= day2).all()
NameError: name 'day' is not defined
2018-05-30 23:45:23,538 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:45:26,734 ERROR: Exception on /api/measures/from/2018/04/24/to/2018/05/01 [GET] [in /Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lucamaiano/Desktop/visualization/app/api/measures.py", line 23, in get_interval_of_measures
    request = Measurements.query_interval_of_measures(day1, day2)
  File "/Users/lucamaiano/Desktop/visualization/app/models.py", line 148, in query_interval_of_measures
    resources = Measurements.query.filter_by(day >= day1).filter_by(day <= day2).all()
NameError: name 'day' is not defined
2018-05-30 23:45:46,364 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:46:59,711 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:47:54,258 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:48:52,922 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:49:39,682 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:50:07,023 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:50:50,735 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-30 23:51:27,261 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 09:58:50,576 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 10:32:49,898 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 11:00:35,731 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 11:12:40,400 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
